/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utviews;


import Client.ClientInitiator;
import com.sun.tools.javac.Main;
import java.awt.Color;
import java.io.IOException;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JPanel;
import server.InitConnection;


/**
 *
 * @author pc
 */
public class home extends javax.swing.JFrame {

    public static int port;
    public static String IpAddress;
    public static int tt;

    /**
     * Creates new form home
     */
    public home() {
        try {
            initComponents();
            setForm(mainItem1);
            setIpAdressC();
            setPort();
            port = Integer.parseInt(txtPC.getText());
        } catch (SocketException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnHide = new javax.swing.JPanel();
        hidePG = new javax.swing.JLabel();
        btnMinMax = new javax.swing.JPanel();
        fullMax = new javax.swing.JLabel();
        btnExits = new javax.swing.JPanel();
        exitsPG = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        listItem = new javax.swing.JPanel();
        item1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        mainItem1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIPC = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtIPK = new javax.swing.JTextField();
        txtPK = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnRF = new javax.swing.JPanel();
        btnRefesh = new javax.swing.JLabel();
        btnCTC = new javax.swing.JPanel();
        btnConnectToClient = new javax.swing.JLabel();
        btnCTS = new javax.swing.JPanel();
        btnConnectToServer = new javax.swing.JLabel();
        mainItem2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(517, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHide.setBackground(new java.awt.Color(255, 255, 255));

        hidePG.setBackground(new java.awt.Color(255, 255, 255));
        hidePG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidePG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minus.png"))); // NOI18N
        hidePG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hidePG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hidePGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hidePGMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHideLayout = new javax.swing.GroupLayout(btnHide);
        btnHide.setLayout(btnHideLayout);
        btnHideLayout.setHorizontalGroup(
            btnHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hidePG, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnHideLayout.setVerticalGroup(
            btnHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hidePG, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        btnMinMax.setBackground(new java.awt.Color(255, 255, 255));

        fullMax.setBackground(new java.awt.Color(255, 255, 255));
        fullMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full-screen.png"))); // NOI18N
        fullMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullMaxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMinMaxLayout = new javax.swing.GroupLayout(btnMinMax);
        btnMinMax.setLayout(btnMinMaxLayout);
        btnMinMaxLayout.setHorizontalGroup(
            btnMinMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullMax, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnMinMaxLayout.setVerticalGroup(
            btnMinMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullMax, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnMinMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 30));

        btnExits.setBackground(new java.awt.Color(255, 255, 255));

        exitsPG.setBackground(new java.awt.Color(255, 255, 255));
        exitsPG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitsPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/power-off.png"))); // NOI18N
        exitsPG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitsPGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitsPGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitsPGMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitsLayout = new javax.swing.GroupLayout(btnExits);
        btnExits.setLayout(btnExitsLayout);
        btnExitsLayout.setHorizontalGroup(
            btnExitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitsPG, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnExitsLayout.setVerticalGroup(
            btnExitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitsPG, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnExits, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 30));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(669, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(52, 58, 64));
        menu.setPreferredSize(new java.awt.Dimension(200, 470));
        menu.setLayout(new java.awt.BorderLayout());

        listItem.setBackground(new java.awt.Color(52, 58, 64));
        listItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item1.setBackground(new java.awt.Color(52, 58, 64));
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                item1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                item1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Home");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhome.png"))); // NOI18N

        javax.swing.GroupLayout item1Layout = new javax.swing.GroupLayout(item1);
        item1.setLayout(item1Layout);
        item1Layout.setHorizontalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        item1Layout.setVerticalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, item1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(item1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        listItem.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        item2.setBackground(new java.awt.Color(52, 58, 64));
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                item2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                item2MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/infon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Infomation");

        javax.swing.GroupLayout item2Layout = new javax.swing.GroupLayout(item2);
        item2.setLayout(item2Layout);
        item2Layout.setHorizontalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        item2Layout.setVerticalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        listItem.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 200, 40));

        menu.add(listItem, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        menuPanel.setOpaque(false);
        menuPanel.setLayout(new java.awt.BorderLayout());

        mainItem1.setBackground(new java.awt.Color(244, 246, 249));
        mainItem1.setPreferredSize(new java.awt.Dimension(600, 470));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CONTROL");

        jLabel5.setText("IP Adress");

        jLabel12.setText("Port");

        jLabel13.setText("IP Adress");

        jLabel14.setText("Port");

        txtIPC.setEditable(false);

        jLabel15.setText("Lưu ý:");

        jLabel16.setText("Vui lòng nhập đầy đủ thông tin trước khi kết nối");

        jLabel17.setText("Hãy liên hệ với chúng tôi khi cần thiết");

        btnRefesh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRefesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh (1).png"))); // NOI18N
        btnRefesh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefeshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefeshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefeshMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRFLayout = new javax.swing.GroupLayout(btnRF);
        btnRF.setLayout(btnRFLayout);
        btnRFLayout.setHorizontalGroup(
            btnRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRefesh, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnRFLayout.setVerticalGroup(
            btnRFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRefesh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnConnectToClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConnectToClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/compare.png"))); // NOI18N
        btnConnectToClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectToClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConnectToClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConnectToClientMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCTCLayout = new javax.swing.GroupLayout(btnCTC);
        btnCTC.setLayout(btnCTCLayout);
        btnCTCLayout.setHorizontalGroup(
            btnCTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConnectToClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnCTCLayout.setVerticalGroup(
            btnCTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConnectToClient, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        btnConnectToServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConnectToServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/compare.png"))); // NOI18N
        btnConnectToServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectToServerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConnectToServerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConnectToServerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCTSLayout = new javax.swing.GroupLayout(btnCTS);
        btnCTS.setLayout(btnCTSLayout);
        btnCTSLayout.setHorizontalGroup(
            btnCTSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCTSLayout.createSequentialGroup()
                .addComponent(btnConnectToServer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCTSLayout.setVerticalGroup(
            btnCTSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConnectToServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainItem1Layout = new javax.swing.GroupLayout(mainItem1);
        mainItem1.setLayout(mainItem1Layout);
        mainItem1Layout.setHorizontalGroup(
            mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainItem1Layout.createSequentialGroup()
                .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainItem1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainItem1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIPC)
                            .addComponent(txtPC, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIPK, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainItem1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainItem1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainItem1Layout.setVerticalGroup(
            mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainItem1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(txtIPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(mainItem1, java.awt.BorderLayout.CENTER);

        mainItem2.setBackground(new java.awt.Color(244, 246, 249));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INFORMTION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Author:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Copyright:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nguyễn Ngọc Anh - CNTT 1504");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("DNU ");

        javax.swing.GroupLayout mainItem2Layout = new javax.swing.GroupLayout(mainItem2);
        mainItem2.setLayout(mainItem2Layout);
        mainItem2Layout.setHorizontalGroup(
            mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainItem2Layout.createSequentialGroup()
                .addGroup(mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainItem2Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel6))
                    .addGroup(mainItem2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        mainItem2Layout.setVerticalGroup(
            mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainItem2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        menuPanel.add(mainItem2, java.awt.BorderLayout.CENTER);

        getContentPane().add(menuPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void setPort() {
        Random rd = new Random();
        int p = rd.nextInt(100);
        p = (p + 1) * 100;
        String pt = "" + p;
        txtPC.setText(pt);
    }

    public void setIpAdressC() throws SocketException, UnknownHostException {
        try (final DatagramSocket socket = new DatagramSocket()) {
            socket.connect(InetAddress.getByName("8.8.8.8"), 10002);
            String ip = socket.getLocalAddress().getHostAddress();
            txtIPC.setText(ip);
        }
    }

    private void setForm(JComponent com) {
        menuPanel.removeAll();
        menuPanel.add(com);
        menuPanel.repaint();
        menuPanel.revalidate();
    }


    private void hidePGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePGMouseEntered
        changeColor(btnHide, new Color(240, 240, 240));
    }//GEN-LAST:event_hidePGMouseEntered

    private void hidePGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePGMouseExited
        // TODO add your handling code here:
        changeColor(btnHide, new Color(255, 255, 255));
    }//GEN-LAST:event_hidePGMouseExited

    private void hidePGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePGMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(home.HIDE_ON_CLOSE);
    }//GEN-LAST:event_hidePGMouseClicked

    private void fullMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseEntered
        // TODO add your handling code here:
        changeColor(btnMinMax, new Color(240, 240, 240));
    }//GEN-LAST:event_fullMaxMouseEntered

    private void fullMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseExited
        // TODO add your handling code here:
        changeColor(btnMinMax, new Color(255, 255, 255));
    }//GEN-LAST:event_fullMaxMouseExited

    private void fullMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != home.MAXIMIZED_BOTH) {
            this.setExtendedState(home.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(home.NORMAL);
        }
    }//GEN-LAST:event_fullMaxMouseClicked

    private void exitsPGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitsPGMouseEntered
        // TODO add your handling code here:
        changeColor(btnExits, new Color(240, 240, 240));
    }//GEN-LAST:event_exitsPGMouseEntered

    private void exitsPGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitsPGMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitsPGMouseClicked

    private void exitsPGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitsPGMouseExited
        // TODO add your handling code here:
        changeColor(btnExits, new Color(255, 255, 255));
    }//GEN-LAST:event_exitsPGMouseExited

    private void item1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseEntered
        // TODO add your handling code here:
        changeColor(item1, new Color(0, 123, 255));
    }//GEN-LAST:event_item1MouseEntered

    private void item1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseExited
        // TODO add your handling code here:
        changeColor(item1, new Color(52, 58, 64));
    }//GEN-LAST:event_item1MouseExited

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        // TODO add your handling code here:
        setForm(mainItem1);
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        // TODO add your handling code here:
        setForm(mainItem2);
    }//GEN-LAST:event_item2MouseClicked

    private void item2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseEntered
        // TODO add your handling code here:
        changeColor(item2, new Color(0, 123, 255));
    }//GEN-LAST:event_item2MouseEntered

    private void item2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseExited
        // TODO add your handling code here:
        changeColor(item2, new Color(52, 58, 64));
    }//GEN-LAST:event_item2MouseExited

    private void btnRefeshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshMouseClicked
        setPort();
    }//GEN-LAST:event_btnRefeshMouseClicked

    private void btnRefeshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshMouseEntered
        changeColor(btnRF, new Color(247, 202, 92));
    }//GEN-LAST:event_btnRefeshMouseEntered

    private void btnRefeshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshMouseExited
        changeColor(btnRF, new Color(240, 240, 240));
    }//GEN-LAST:event_btnRefeshMouseExited

    private void btnConnectToClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectToClientMouseClicked
        int port = Integer.parseInt(txtPC.getText());
        new InitConnection(port);
    }//GEN-LAST:event_btnConnectToClientMouseClicked

    private void btnConnectToClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectToClientMouseEntered
        changeColor(btnCTC, new Color(247, 202, 92));
    }//GEN-LAST:event_btnConnectToClientMouseEntered

    private void btnConnectToClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectToClientMouseExited
        changeColor(btnCTC, new Color(240, 240, 240));
    }//GEN-LAST:event_btnConnectToClientMouseExited

    private void btnConnectToServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectToServerMouseClicked
        int port = Integer.parseInt(txtPK.getText());
        new ClientInitiator(txtIPK.getText(), port);
    }//GEN-LAST:event_btnConnectToServerMouseClicked

    private void btnConnectToServerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectToServerMouseEntered
        changeColor(btnCTS, new Color(247, 202, 92));
    }//GEN-LAST:event_btnConnectToServerMouseEntered

    private void btnConnectToServerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectToServerMouseExited
        changeColor(btnCTS, new Color(240, 240, 240));
    }//GEN-LAST:event_btnConnectToServerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCTC;
    private javax.swing.JPanel btnCTS;
    private javax.swing.JLabel btnConnectToClient;
    private javax.swing.JLabel btnConnectToServer;
    private javax.swing.JPanel btnExits;
    private javax.swing.JPanel btnHide;
    private javax.swing.JPanel btnMinMax;
    private javax.swing.JPanel btnRF;
    private javax.swing.JLabel btnRefesh;
    private javax.swing.JLabel exitsPG;
    private javax.swing.JLabel fullMax;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hidePG;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listItem;
    private javax.swing.JPanel mainItem1;
    private javax.swing.JPanel mainItem2;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField txtIPC;
    private javax.swing.JTextField txtIPK;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPK;
    // End of variables declaration//GEN-END:variables
}
